# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Build firmware for TOTEM"
on: [push, workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_left","totem_right"]'
      alphas: '["qwerty"]'
